export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_FILTERED_PRODUCTS: "SET_FILTERED_PRODUCTS",
    SET_CART_PRODUCTS:"SET_CART_PRODUCTS",
    DELETE_CART_PRODUCT:"DELETE_CART_BOOK",
    INCREASE_CART_ITEM_QUANTITY:"INCREASE_CART_ITEM_QUANTITY",
    DECREASE_CART_ITEM_QUANTITY:"DECREASE_CART_ITEM_QUANTITY"
  };